
platform :ios, '9.0'

target 'RNDemo' do
    # 'node_modules'目录一般位于根目录中,我放到了ReactComponent文件夹下了，修改如下对应的路径
    # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
    pod 'React', :path => './ReactComponent/node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # 如果RN版本 >= 0.45则加入此行
    #'BatchedBridge',    #RN版本高于0.45之后必须导入
    'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',     # 这个模块是用于调试功能的
    # 在这里继续添加你所需要的RN模块
    #'ART',
    #'RCTActionSheet',
    #'RCTAdSupport',
    #'RCTCameraRoll',
    #'RCTGeolocation',
    'RCTPushNotification',
    #'RCTSettings',
    #'RCTVibration',
    'RCTLinkingIOS',
    'RCTAnimation',
    ]

    # 如果你的RN版本 >= 0.42.0，则加入下面这行。
    pod 'yoga', :path => './ReactComponent/node_modules/react-native/ReactCommon/yoga'
    # 这里注意： 如果是0.49以下的RN，则使用下面这条：
    # pod "Yoga", :path => "./ReactComponent/node_modules/react-native/ReactCommon/yoga"

    # 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
    pod 'DoubleConversion', :podspec => './ReactComponent/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => './ReactComponent/node_modules/react-native/third-party-podspecs/glog.podspec'
    # ios9.0以上版本才行
    pod 'Folly', :podspec => './ReactComponent/node_modules/react-native/third-party-podspecs/Folly.podspec'


  target 'RNDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
